"""
Optimize photos for the Friends of Tricentennial website.

Runs automatically on GitHub (see .github/workflows/optimize-images.yml) whenever
someone uploads photos to assets/images/originals/. Developers can also run it locally:

    pip install Pillow
    python scripts/optimize_images.py

What it does for every photo in assets/images/originals/:
  1. Rotates it upright (using the camera's orientation tag) and removes ALL camera
     metadata, including GPS location. Large originals are also capped at 2400 px.
  2. Writes WebP copies at 400 / 800 / 1600 px wide (never enlarging) plus an 800 px JPEG
     fallback to assets/images/optimized/<same folders>/<name>-<width>.webp|jpg
  3. Records size, available widths and dominant color in data/image-manifest.json
  4. Removes optimized files and manifest entries for originals that were deleted.

Photos that were already processed (same content hash) are skipped.
A file that can't be read only produces a warning; the run never fails because of it.
"""

import hashlib
import json
import shutil
import sys
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
ORIGINALS = ROOT / "assets" / "images" / "originals"
OPTIMIZED = ROOT / "assets" / "images" / "optimized"
MANIFEST = ROOT / "data" / "image-manifest.json"

WIDTHS = [400, 800, 1600]
FALLBACK_WIDTH = 800
MAX_ORIGINAL = 2400
WEBP_QUALITY = 75
JPEG_QUALITY = 78
EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}

HELP = (
    "AUTO-GENERATED by scripts/optimize_images.py (runs on GitHub after every photo upload). "
    "Do NOT edit this file by hand. It lists the resized versions of every photo in "
    "assets/images/originals/ so the website can pick the right size for each screen."
)


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def file_hash(path: Path) -> str:
    return hashlib.sha1(path.read_bytes()).hexdigest()[:16]


def sanitize_original(path: Path) -> None:
    """Rewrite the original without metadata (GPS!) and cap its size, if needed."""
    with Image.open(path) as im:
        has_meta = bool(im.info.get("exif")) or bool(im.getexif())
        too_big = max(im.size) > MAX_ORIGINAL
        if not (has_meta or too_big):
            return
        fmt = im.format
        im = ImageOps.exif_transpose(im)
        if too_big:
            im.thumbnail((MAX_ORIGINAL, MAX_ORIGINAL), Image.LANCZOS)
        if fmt == "JPEG":
            im.convert("RGB").save(path, "JPEG", quality=88, optimize=True, progressive=True)
        elif fmt == "PNG":
            im.save(path, "PNG", optimize=True)
        elif fmt == "WEBP":
            im.save(path, "WEBP", quality=88)
        else:
            return
        print(f"  cleaned original (metadata removed{', resized' if too_big else ''}): {rel(path)}")


def dominant_color(im: Image.Image) -> str:
    r, g, b = im.convert("RGB").resize((1, 1), Image.LANCZOS).getpixel((0, 0))
    return f"#{r:02x}{g:02x}{b:02x}"


def flatten(im: Image.Image) -> Image.Image:
    """JPEG can't store transparency: paste onto white."""
    if im.mode in ("RGBA", "LA", "P"):
        im = im.convert("RGBA")
        bg = Image.new("RGB", im.size, (255, 255, 255))
        bg.paste(im, mask=im.split()[-1])
        return bg
    return im.convert("RGB")


def output_stem(path: Path) -> str:
    return path.stem.lower().replace(" ", "-")


def process(path: Path, stem: str) -> dict:
    sanitize_original(path)
    out_dir = OPTIMIZED / path.parent.relative_to(ORIGINALS)
    out_dir.mkdir(parents=True, exist_ok=True)

    with Image.open(path) as im:
        im = ImageOps.exif_transpose(im)
        w, h = im.size
        widths = sorted({min(x, w) for x in WIDTHS})
        for target in widths:
            copy = im.copy()
            if target < w:
                copy = copy.resize((target, round(h * target / w)), Image.LANCZOS)
            if copy.mode not in ("RGB", "RGBA"):
                copy = copy.convert("RGBA" if "A" in copy.getbands() else "RGB")
            copy.save(out_dir / f"{stem}-{target}.webp", "WEBP", quality=WEBP_QUALITY, method=6)

        jpg_w = min(FALLBACK_WIDTH, w)
        jpg = flatten(im.copy())
        if jpg_w < w:
            jpg = jpg.resize((jpg_w, round(h * jpg_w / w)), Image.LANCZOS)
        jpg.save(out_dir / f"{stem}-{jpg_w}.jpg", "JPEG", quality=JPEG_QUALITY, optimize=True, progressive=True)

        return {
            "w": w,
            "h": h,
            "color": dominant_color(im),
            "base": rel(out_dir / stem),
            "widths": widths,
            "jpg": jpg_w,
            "hash": file_hash(path),
        }


def remove_outputs(entry: dict) -> None:
    base = ROOT / entry["base"]
    for target in entry.get("widths", []):
        (base.parent / f"{base.name}-{target}.webp").unlink(missing_ok=True)
    (base.parent / f"{base.name}-{entry.get('jpg')}.jpg").unlink(missing_ok=True)


def main() -> int:
    manifest = {}
    if MANIFEST.exists():
        try:
            manifest = json.loads(MANIFEST.read_text(encoding="utf-8")).get("images", {})
        except (json.JSONDecodeError, OSError) as err:
            print(f"WARNING: manifest unreadable, rebuilding it ({err})")

    originals = sorted(p for p in ORIGINALS.rglob("*") if p.is_file() and p.suffix.lower() in EXTENSIONS)
    seen = {rel(p) for p in originals}
    processed, skipped, failed = 0, 0, 0

    # Remove outputs of deleted photos FIRST, so a replacement photo with the same
    # name but a different extension (hero.jpg -> hero.png) keeps its new files.
    for key in [k for k in manifest if k not in seen]:
        remove_outputs(manifest.pop(key))
        print(f"  removed outputs for deleted photo: {key}")

    # Two photos with the same name in one folder (photo.jpg + photo.png) would
    # overwrite each other's outputs: give them distinct names (photo-jpg, photo-png).
    names = {}
    for path in originals:
        names.setdefault((path.parent, output_stem(path)), []).append(path)

    for path in originals:
        key = rel(path)
        stem = output_stem(path)
        if len(names[(path.parent, stem)]) > 1:
            stem = f"{stem}-{path.suffix.lower().lstrip('.')}"
        entry = manifest.get(key)
        if entry and entry.get("base") != rel(OPTIMIZED / path.parent.relative_to(ORIGINALS) / stem):
            remove_outputs(entry)  # output name changed (a name clash appeared or went away)
            entry = None
        try:
            if entry and entry.get("hash") == file_hash(path) and (ROOT / f"{entry['base']}-{entry['jpg']}.jpg").exists():
                skipped += 1
                continue
            if entry:
                remove_outputs(entry)
            manifest[key] = process(path, stem)
            processed += 1
            print(f"  optimized: {key}")
        except Exception as err:  # one bad file must never break the run
            failed += 1
            print(f"WARNING: could not process {key}: {err}")

    # Clean up empty folders left behind
    if OPTIMIZED.exists():
        for d in sorted((p for p in OPTIMIZED.rglob("*") if p.is_dir()), reverse=True):
            if not any(d.iterdir()):
                shutil.rmtree(d)

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(
        json.dumps({"_help": HELP, "images": dict(sorted(manifest.items()))}, indent=1) + "\n",
        encoding="utf-8",
    )
    print(f"Done: {processed} optimized, {skipped} unchanged, {failed} warnings, {len(manifest)} total.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
